name: CI

on:
  pull_request:
    branches: ["master"]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install Deps
        uses: npm i
      - name: Cypress
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: npx serve build
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          browser: chrome
